### ISSUE TITLE
Helmet overlay should be disabled or toggleable

### ISSUE THREAD

**Issue by Z5aI69A61** [Raicuparta/nomai-vr#230]
The helmet that is visible around the border of the screen is kind of redundant in VR. Our FOV is already limited by the headset itself, so adding another layer beyond that is distracting, at least in my opinion.

**Comment by Raicuparta** [comment]
I'm a bit reluctant to add configurable stuff because that increases the chance of me introducing bugs that I don't notice (because I don't test all possible configurable options).

I'd prefer to somehow change the size of the helmet depending on the VR headset being used. For instance, with my Oculus, I only really see the helmet when I'm moving my head around. I assume for you it is visible at all times?

**Comment by Z5aI69A61** [comment]
@Raicuparta The helmet is always visible for me at the very bottom, as well as parts in the upper left and upper right (using a Vive Pro). Being able to see it clearly when I'm moving my head is also pretty distracting for me, though. Maybe it would be better if you were to reduce the lag time on its movement? I dunno. I'm not a dev. :P

**Comment by Raicuparta** [comment]
Closed by #239 
(will be available on release 0.38)
