### ISSUE TITLE
Always hide helmet HUD during conversations, still show notifications

### ISSUE THREAD

**Issue by senritsu** [Raicuparta/nomai-vr#286]
A continuation of #269 (fixed in #284).

After #284 there exists a config option to hide the HUD in conversations, but it hides all helmet HUD elements, in particular this includes notifications (which tend to pop up during conversations and are important at times). If notifications would stay visible, there would be no necessity to have a setting, since there would be no currently known drawbacks. 

To get this to an optimal state, the logic to hide the HUD would need to be enhanced to **not** hide the notification overlay, just everything else. With that, the config option could be removed again, and the HUD hiding would be elevated to default behaviour.

**Comment by Raicuparta** [comment]
This might be helpful: `HelmetHUD.cs` already has something that is selecting only the HUD notifications:
```
var notifications = FindObjectOfType<SuitNotificationDisplay>().GetComponent<RectTransform>();
```

(which btw, could probably be optimized by using `FindComponentInChildren` instead of `FindObjectOfType`).

Another approach would be hiding only the individual parts that are problematic: the fuel / oxygen / health status circle, the minimap, the gravity strength indicator, and the gyroscope. Could prevent us accidentally hiding something else unexpected.

**Comment by Raicuparta** [comment]
Just realized, the game already hides part of the HUD automatically (gyroscope and gravity strength indicator). So we only need to hide the minimap and player status thing.
