### ISSUE TITLE
Few features that could make the game/mod less clunky.

### ISSUE THREAD

**Issue by Somiaz** [Raicuparta/nomai-vr#293]
Swiping your hand to switch between things is quite annoying, maybe introduce new buttons on tools and on the ship to press to switch between signals and to look around in a landed scout, headlights and your own flashlight.
Also try move the player more forward when buckled into your ship, this can help the player so they aren't 3 feet into the seat.
The feet on the floor could rotate more as they player moves the head every frame, this can help in zero-g as well as positioning.
The hands could be animated when you use the grip and trigger buttons.
Fullscreen on desktop, this makes anyone watching see things in better quality.

**Comment by Raicuparta** [comment]
> Swiping your hand to switch between things is quite annoying, maybe introduce new buttons on tools and on the ship to press to switch between signals and to look around in a landed scout, headlights and your own flashlight.

Yes this is an obvious limitation right now. Not sure how I'll fix it yet, need something that's feasible to implement.

> Also try move the player more forward when buckled into your ship, this can help the player so they aren't 3 feet into the seat.

This is due to scale issues, the ship's scale simply makes no sense, it's way too big. Moving the player forward might help, but the game acts weirdly when I try to force the player to some position inside the ship (often killing the player). In any way, the scale / position problem has been on my mind for a while, so I'll re-open that issue.

> The feet on the floor could rotate more as they player moves the head every frame, this can help in zero-g as well as positioning.

Not gonna happen.

> The hands could be animated when you use the grip and trigger buttons.

Also not gonna happen.

> Fullscreen on desktop, this makes anyone watching see things in better quality.

I'll open an issue about this. But if you're gonna do screen capture, I recommend mirroring your VR device if possible, since the game window will always be more cropped and super low resolution (independently of the resolution you pick in the game).

Closing this issue as it discusses too many unrelated ponints.
