### ISSUE TITLE
Issue during startup: could not find actions file

### ISSUE THREAD

**Issue by adriansun1** [Raicuparta/nomai-vr#374]
Hi, i'm getting the following error when trying to start the game from the OW mod manager

![ow1](https://user-images.githubusercontent.com/34041016/93558643-be9f1880-f932-11ea-8d65-54bbef8da57c.PNG)
![ow2](https://user-images.githubusercontent.com/34041016/93563122-1d1cc480-f93c-11ea-82fc-1fd9bc599ad4.PNG)

What I've tried:
- running in admin
- reinstalling mod/ game
- manual install
- starting with steam vr started/ not started

I can get past the first error by copy pasting the actions.json from the mod directory straight into the game dir `...\Outerwilds_Data\StreamingAssets\SteamVr` 
but am unable to get the rest of the mod running. In my steam bindings ui, I'm don't see the outer wild application

**Comment by adriansun1** [comment]
fixed by moving the actions.json into  `...\Outerwilds_Data\StreamingAssets\SteamVr` then starting SteamVR and turning on both controllers before starting the game. still get some errors about haptic vibration but the game works and the controls seem to work fine. cant wait to play thank you guys for making this mod 😄

**Comment by Raicuparta** [comment]
For anyone reading this in the future: the errors in these screenshots are all kinda supposed to happen (because I wasn't able to fix or suppress them). Moving the actions.json file to `...\Outerwilds_Data\StreamingAssets\SteamVR` does make that one error go away, but that doesn't really help with anything. The real fix here is to make sure all controllers are connected when starting the game.
