### ISSUE TITLE
After opening the map the game freezes (and not responding)

### ISSUE THREAD

**Issue by GitHubUser1989** [Raicuparta/nomai-vr#377]
I have HTC Vive. This mod is awsome, but after opening up the map of the solar system in the space shuttle makes the whole game freeze, i got error messages like this:

- Quantum moon orbit position occupied! Aborting collapse.. Stack trace: Unity 18
- NullReferenceException: Object reference not set to an instance of an object. Stack trace:  Unity 77
NomaiVR.SmoothFollowCameraRotation.LateUpdate ()

etc.

**Comment by Raicuparta** [comment]
By space shuttle do you mean the player's ship or something else?

**Comment by GitHubUser1989** [comment]
Yes the players's ship.

**Comment by Werschon** [comment]
I noticed this bug too. It always happens when i use the map for too long. The only thing that helps is trying to close the window (by pressing x on the desktop) and when the prompt appears telling me the game does not react I hit "try to restore the program" or whatever it's called. That usually does the trick.

**Comment by Raicuparta** [comment]
Probably fixed by 14229cc
