### ISSUE TITLE
Spaceship scout doesn't work in space.

### ISSUE THREAD

**Issue by Quplet** [Raicuparta/nomai-vr#461]
* Game Version: 1.1.72
* OWML Version: 2.1.0
* NomaiVR Version: 2.2.0
* VR hardware: Oculus Quest 2 w/ link

 
While drifting through space in the spaceship, the scout launched seems to attach to the ship. Pictures taken from it are from the ship, not an object heading in the direction I shot the scout. I believe the scout may be preemptively returning and attaching itself to the ship. Can comment with screenshots if needed. To recreate, simply fly into space, don't be within a planet's gravitational effect, fire the scout and take snapshots.

**Comment by Quplet** [comment]
[Youtube](https://youtu.be/AoQaYwSCYs0)
Video I took displaying the bug. It is possible that since I altered the world scale using SteamVR as a test, that it somehow caused it, yet at the time of this recording I had reset it to default. It is the only thing I have don't that would make my game different from most others in the case no one else can reproduce the effect.

**Comment by Quplet** [comment]
Well, damn just uninstalled the mod and ran unmodded OW and the problem still persists. I guess its a problem with my OW not the mod.

**Comment by Raicuparta** [comment]
I don't think that's even a bug at all, I think it's just the probe being slower than you might expect, so it looks almost like it's standing still? If you try flying closer to a planet and shooting the probe at it, you'll more easily notice the movement. Anyway I'll close this since it's not a NomaiVR bug, even if it is a bug.
